name: integration

on:
  push:
    branches: 
      - "*"
  pull_request:
    branches: 
      - main

env:
  ENV: testing

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v5

    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: stable
    
    - name: Install Dependencies
      run: go build

    - name: Run Tests
      run: go test ./... -coverpkg=./... -coverprofile=coverage.txt

    - name: Lint Project and Check Formatting
      uses: golangci/golangci-lint-action@v8
      with:
        version: latest
    
    - name: Codecov
      uses: codecov/codecov-action@v5
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}

  analyze:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write
      
    strategy:
      fail-fast: false

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v5
      
    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: stable

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: go

    - name: AutoBuild
      uses: github/codeql-action/autobuild@v3

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: /language:go